# reasoning_analysis_config.yaml

# Configuration for ReasoningAnalyzer

similarity_threshold: 0.8  # Threshold for considering two reasonings similar

embedding_model: 'sentence-transformers/all-MiniLM-L6-v2'  # Model for generating text embeddings

clustering:
  min_cluster_size: 5  # Minimum size of clusters
  min_samples: 1  # Minimum samples in a neighborhood for a point to be considered a core point

summarization:
  method: 'LLM'  # Method for summarizing clusters, e.g., using an LLM

visualization:
  output_formats: ['html', 'png']  # Formats for visualizations
  interactive: true  # Whether visualizations should be interactive
